name: octokit
description: Dart toolkit for the GitHub GraphQL API to run autogenerate GraphQL query.
version: 0.0.3
homepage: https://github.com/vincenzopalazzo/octokit.dart

environment:
  sdk: '>=2.15.1 <3.0.0'

false_secrets:
  - /credentials.json

dependencies:
  graphql: ^5.0.1
  json_annotation: ^4.6.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  json_serializable: ^6.1.5
  graphql_codegen: ^0.11.0
  build_runner: ^2.0.3
  gql: ^0.13.0
