name: octokit
description: Dart toolkit for the GitHub GraphQL API.
version: 0.1.0
homepage: https://github.com/vincenzopalazzo/octokit.dart

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  graphql: ^5.0.1-beta.3
  json_annotation: ^4.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  json_serializable: ^4.1.2
  graphql_codegen: ^0.5.0-alpha.1
  build_runner: ^2.0.3
