name: octokit
description: Dart toolkit for the GitHub GraphQL API.
version: 0.0.4
homepage: https://github.com/vincenzopalazzo/octokit.dart

environment:
  sdk: '>=2.15.1 <3.0.0'

false_secrets:
  - /credentials.json

dependencies:
  graphql: ^5.1.3
  json_annotation: ^4.7.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  json_serializable: ^6.1.5
  graphql_codegen: ^0.12.0-beta.7
  build_runner: ^2.0.3
