name: changelog_exatractor
description: Example of Changelog Extractor with octokit.dart
version: 1.0.0
homepage: https://github.com/vincenzopalazzo/octokit.dart

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.7
  graphql_codegen: ^0.11.2
  lints: ^1.0.0
  gql: ^0.14.0
  json_serializable: ^4.1.2
dependencies: 
  octokit: ^0.0.3
