name: Publish octokit.dart

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: false
          skipTests: false
          dry_run: false
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
